# Generated by Django 4.1.5 on 2023-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
