# Generated by Django 4.1.5 on 2023-01-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_remove_song_image_remove_song_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
